name: 'setup node'
description: 'Setup Node'

inputs:
  node-version:
    description: 'Node.js version to use. If not provided, version is read from .node-version file'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && '.node-version' || '' }}
        cache: 'yarn'
        cache-dependency-path: yarn.lock
