name: 'setup node'
description: 'Setup Node'

inputs:
  node-version:
    description: 'Node.js version to use. If not provided, version is read from .node-version file'
    required: false

  cache:
    description: 'Used to specify a package manager for caching in the default directory'
    required: false

  cache-dependency-path:
    description: 'Used to specify the path to a dependency file'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && '.node-version' || '' }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
