name: 'setup and install'
description: 'Setup Node and Install Dependencies'

inputs:
  node-version:
    description: 'Node.js version to use. If not provided, version is read from .node-version file'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      uses: ./.github/actions/deps-install
