name: 🚦 Git Checks

on:
  workflow_call:

jobs:
  block-fixup-merge:
    name: 🚫 Blocked Merge by Fixup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Block fixup commit merge
        run: |
          if git log --format=%s ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep -iE "^fixup!"; then
            echo "Fixup commits are not allowed. Please squash them before merging."
            exit 1
          fi

  commitlint:
    name: 🧾 Commit Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-install

      - name: Commits Check
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
